title: nihilux
logo: "/assets/nihilux_logo.png"
theme: jekyll-theme-minimal
plugins:
  - jekyll-polyglot
  - jekyll-minifier
markdown: kramdown
kramdown:
  input: GFM
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: true
lang_from_path: true
collections:
  projects:
    - name: nihilux/publication
      url: https://publication.nihilux.org
      description:
        en: an open source house of publication
        fr: une maison d'édition open source
    - name: nihilux/photos
      url: https://photos.nihilux.org
      description: 
        en: a web corner dedicated to photography
        fr: un coin du web dédié à la photographie
      disabled: true
