title: nihilux
repository: nihilux-org/nihilux
logo: "/assets/nihilux_logo.png"
theme: jekyll-theme-minimal
encoding: utf-8
url: https://www.nihilux.org
include: ["CNAME"]
baseurl: ""
plugins:
  - jekyll-polyglot
  - jekyll-minifier
markdown: kramdown
kramdown:
  input: GFM
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: true
lang_from_path: true
