title: nihilux
repository: nihilux-org/nihilux
logo: "/assets/nihilux_logo.png"
theme: jekyll-theme-minimal
encoding: utf-8
plugins:
  - jekyll-polyglot
  - jekyll-minifier
  - jekyll-github-metadata
markdown: kramdown
kramdown:
  input: GFM
languages: ["en", "fr"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css", "README.md"]
parallel_localization: true
lang_from_path: true
